name: ATM API

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  BUILD-AND-TEST:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./code
      run: npm install

    - name: Run Unit and Integration tests
      working-directory: ./code
      run: npm run test

  PUSH-TO-DOCKER:
    runs-on: ubuntu-latest
    needs: [BUILD-AND-TEST]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./code
        file: ./code/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/atm-api:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/atm-api:latest
